# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 420)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 94, 226, 116))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.generated_password_output = QtWidgets.QLineEdit(parent=self.widget)
        self.generated_password_output.setObjectName("generated_password_output")
        self.gridLayout_2.addWidget(self.generated_password_output, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Lowercase = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_Lowercase.setObjectName("checkBox_Lowercase")
        self.gridLayout.addWidget(self.checkBox_Lowercase, 0, 0, 1, 1)
        self.checkBox_Uppercase = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_Uppercase.setObjectName("checkBox_Uppercase")
        self.gridLayout.addWidget(self.checkBox_Uppercase, 0, 1, 1, 1)
        self.checkBox_Symbols = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_Symbols.setObjectName("checkBox_Symbols")
        self.gridLayout.addWidget(self.checkBox_Symbols, 1, 0, 1, 1)
        self.checkBox_Digits = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_Digits.setObjectName("checkBox_Digits")
        self.gridLayout.addWidget(self.checkBox_Digits, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.length_input = QtWidgets.QLineEdit(parent=self.widget)
        self.length_input.setObjectName("length_input")
        self.gridLayout_2.addWidget(self.length_input, 2, 0, 1, 1)
        self.generate_button = QtWidgets.QPushButton(parent=self.widget)
        self.generate_button.setObjectName("generate_button")
        self.gridLayout_2.addWidget(self.generate_button, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generated_password_output.setPlaceholderText(_translate("MainWindow", "here will be your new password"))
        self.checkBox_Lowercase.setText(_translate("MainWindow", "Lowercase"))
        self.checkBox_Uppercase.setText(_translate("MainWindow", "Uppercase"))
        self.checkBox_Symbols.setText(_translate("MainWindow", "Symbols"))
        self.checkBox_Digits.setText(_translate("MainWindow", "Digits"))
        self.length_input.setPlaceholderText(_translate("MainWindow", "Password Length:"))
        self.generate_button.setText(_translate("MainWindow", "Generate"))
