# Form implementation generated from reading ui file 'generator_parolei.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class PasswordGenerator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 420)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 50, 460, 113))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_password = QtWidgets.QLineEdit(parent=self.widget)
        self.line_password.setObjectName("line_password")
        self.horizontalLayout.addWidget(self.line_password)
        self.btn_copy = QtWidgets.QPushButton(parent=self.widget)
        self.btn_copy.setObjectName("btn_copy")
        self.horizontalLayout.addWidget(self.btn_copy)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slider_lenght = QtWidgets.QSlider(parent=self.widget)
        self.slider_lenght.setMaximum(100)
        self.slider_lenght.setProperty("value", 12)
        self.slider_lenght.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_lenght.setObjectName("slider_lenght")
        self.horizontalLayout_2.addWidget(self.slider_lenght)
        self.spin_lenght = QtWidgets.QSpinBox(parent=self.widget)
        self.spin_lenght.setMaximum(100)
        self.spin_lenght.setProperty("value", 12)
        self.spin_lenght.setObjectName("spin_lenght")
        self.horizontalLayout_2.addWidget(self.spin_lenght)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_lower = QtWidgets.QPushButton(parent=self.widget)
        self.btn_lower.setCheckable(True)
        self.btn_lower.setChecked(True)
        self.btn_lower.setObjectName("btn_lower")
        self.horizontalLayout_3.addWidget(self.btn_lower)
        self.btn_upper = QtWidgets.QPushButton(parent=self.widget)
        self.btn_upper.setCheckable(True)
        self.btn_upper.setChecked(True)
        self.btn_upper.setObjectName("btn_upper")
        self.horizontalLayout_3.addWidget(self.btn_upper)
        self.btn_digits = QtWidgets.QPushButton(parent=self.widget)
        self.btn_digits.setCheckable(True)
        self.btn_digits.setChecked(True)
        self.btn_digits.setObjectName("btn_digits")
        self.horizontalLayout_3.addWidget(self.btn_digits)
        self.btn_sumbols = QtWidgets.QPushButton(parent=self.widget)
        self.btn_sumbols.setCheckable(True)
        self.btn_sumbols.setObjectName("btn_sumbols")
        self.horizontalLayout_3.addWidget(self.btn_sumbols)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_copy.setText(_translate("MainWindow", "Copy"))
        self.btn_lower.setText(_translate("MainWindow", "a-z"))
        self.btn_upper.setText(_translate("MainWindow", "A-Z"))
        self.btn_digits.setText(_translate("MainWindow", "0-9"))
        self.btn_sumbols.setText(_translate("MainWindow", "#$%"))
